use crate::ast::{Makefile, Rule};
use crate::graph::DependencyGraph;
use std::collections::HashMap;

fn clean_make_cmd_for_ninja(
    raw: &str,
    makefile: &Makefile,
    target: &str,
    prereqs: &[String],
) -> String {
    let mut s = raw.trim();
    while s.starts_with('@') || s.starts_with('-') || s.starts_with('+') {
        s = s[1..].trim_start();
    }
    let expanded = crate::parser::expand_variables(s, makefile, Some(target), prereqs);
    expanded.replace('$', "$$")
}

/// Emits standard Ninja build syntax from an evaluated Makefile AST and graph
pub fn emit_ninja(
    makefile: &Makefile,
    _graph: &DependencyGraph,
    default_goal: Option<&str>,
) -> String {
    let mut out = String::new();
    out.push_str("# Automatically generated by maked --emit-ninja\n");
    out.push_str("ninja_required_version = 1.3\n\n");

    let mut rule_counter = 0usize;
    let mut rule_names: HashMap<String, String> = HashMap::new();
    let mut rule_cmd_keys: HashMap<String, String> = HashMap::new();

    let mut sorted_rules: Vec<&Rule> = makefile.rules.values().collect();
    sorted_rules.sort_by(|a, b| a.target.cmp(&b.target));

    for rule in &sorted_rules {
        if rule.commands.is_empty() || rule.is_phony {
            continue;
        }

        let cleaned_cmds: Vec<String> = rule
            .commands
            .iter()
            .map(|c| clean_make_cmd_for_ninja(c, makefile, &rule.target, &rule.prereqs))
            .collect();
        let cmd_key = cleaned_cmds.join(" && ");
        rule_cmd_keys.insert(rule.target.clone(), cmd_key.clone());

        if let std::collections::hash_map::Entry::Vacant(slot) = rule_names.entry(cmd_key) {
            let r_name = format!("rule_{rule_counter}");
            rule_counter += 1;
            out.push_str(&format!("rule {r_name}\n"));
            out.push_str(&format!("  command = {}\n\n", slot.key()));
            slot.insert(r_name);
        }
    }

    for rule in &sorted_rules {
        let prereqs_str = rule.prereqs.join(" ");
        if rule.is_phony || (rule.commands.is_empty() && !rule.prereqs.is_empty()) {
            out.push_str(&format!("build {}: phony {}\n", rule.target, prereqs_str));
        } else if !rule.commands.is_empty() {
            let cmd_key = rule_cmd_keys.get(&rule.target).unwrap();
            let r_name = rule_names.get(cmd_key).unwrap();
            out.push_str(&format!(
                "build {}: {} {}\n",
                rule.target, r_name, prereqs_str
            ));
        }
    }

    if let Some(goal) = default_goal {
        out.push_str(&format!("\ndefault {goal}\n"));
    } else if let Some(ref dt) = makefile.default_target {
        out.push_str(&format!("\ndefault {dt}\n"));
    }

    out
}

/// Natively parses build.ninja syntax into a Makefile AST
pub fn parse_ninja_content(content: &str) -> Result<Makefile, String> {
    let mut makefile = Makefile::new();
    let mut rules_map: HashMap<String, String> = HashMap::new();
    let mut vars: HashMap<String, String> = HashMap::new();
    let mut current_rule_name: Option<String> = None;
    let mut default_target: Option<String> = None;

    let lines: Vec<&str> = content.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i];
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with('#') {
            i += 1;
            continue;
        }

        if line.starts_with(' ') || line.starts_with('\t') {
            // Indented line: belongs to current rule definition
            if let Some(ref r_name) = current_rule_name {
                if let Some(eq_idx) = trimmed.find('=') {
                    let key = trimmed[..eq_idx].trim();
                    let val = trimmed[eq_idx + 1..].trim();
                    if key == "command" {
                        rules_map.insert(r_name.clone(), val.to_string());
                    }
                }
            }
            i += 1;
            continue;
        }

        current_rule_name = None;

        if let Some(rest) = trimmed.strip_prefix("rule ") {
            let r_name = rest.trim().to_string();
            current_rule_name = Some(r_name);
            i += 1;
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("default ") {
            let targets: Vec<&str> = rest.split_whitespace().collect();
            if let Some(first) = targets.first() {
                default_target = Some(first.to_string());
            }
            i += 1;
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("build ") {
            // Syntax: build out1 out2: rule_name in1 in2 [| implicit] [|| order_only]
            if let Some(colon_idx) = rest.find(':') {
                let outs_part = &rest[..colon_idx];
                let ins_part = &rest[colon_idx + 1..];

                let outputs: Vec<String> = outs_part
                    .split_whitespace()
                    .map(|s| s.to_string())
                    .collect();

                let ins_clean = ins_part.split('|').next().unwrap_or(ins_part).trim();
                let ins_tokens: Vec<&str> = ins_clean.split_whitespace().collect();

                if let Some((rule_name, prereqs)) = ins_tokens.split_first() {
                    let prereqs_vec: Vec<String> = prereqs.iter().map(|s| s.to_string()).collect();
                    let is_phony = *rule_name == "phony";

                    let commands = if is_phony {
                        Vec::new()
                    } else if let Some(cmd) = rules_map.get(*rule_name) {
                        // Expand $out, $in
                        let mut final_cmd = cmd.clone();
                        final_cmd = final_cmd.replace("$out", &outputs.join(" "));
                        final_cmd = final_cmd.replace("${out}", &outputs.join(" "));
                        final_cmd = final_cmd.replace("$in", &prereqs_vec.join(" "));
                        final_cmd = final_cmd.replace("${in}", &prereqs_vec.join(" "));
                        vec![final_cmd]
                    } else {
                        Vec::new()
                    };

                    for out_tgt in outputs {
                        makefile.add_rule(Rule {
                            target: out_tgt,
                            prereqs: prereqs_vec.clone(),
                            commands: commands.clone(),
                            is_phony,
                            line_number: i + 1,
                        });
                    }
                }
            }
            i += 1;
            continue;
        }

        if let Some(eq_idx) = trimmed.find('=') {
            let key = trimmed[..eq_idx].trim().to_string();
            let val = trimmed[eq_idx + 1..].trim().to_string();
            vars.insert(key.clone(), val.clone());
            makefile.set_var(key, val);
        }

        i += 1;
    }

    if let Some(def_tgt) = default_target {
        makefile.default_target = Some(def_tgt);
    }

    Ok(makefile)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ninja_emit_and_parse_roundtrip() {
        let mut mf = Makefile::new();
        mf.add_rule(Rule {
            target: "app".to_string(),
            prereqs: vec!["main.o".to_string(), "util.o".to_string()],
            commands: vec!["gcc main.o util.o -o app".to_string()],
            is_phony: false,
            line_number: 1,
        });
        mf.add_rule(Rule {
            target: "all".to_string(),
            prereqs: vec!["app".to_string()],
            commands: vec![],
            is_phony: true,
            line_number: 5,
        });

        let graph = DependencyGraph::from_makefile(&mf);
        let ninja_text = emit_ninja(&mf, &graph, Some("all"));

        assert!(ninja_text.contains("rule rule_0"));
        assert!(ninja_text.contains("command = gcc main.o util.o -o app"));
        assert!(ninja_text.contains("build all: phony app"));
        assert!(ninja_text.contains("default all"));

        // Now test parse_ninja_content
        let parsed_mf = parse_ninja_content(&ninja_text).unwrap();
        assert_eq!(parsed_mf.default_target, Some("all".to_string()));
        let all_rule = parsed_mf.get_rule("all").unwrap();
        assert!(all_rule.is_phony);
        assert_eq!(all_rule.prereqs, vec!["app"]);

        let app_rule = parsed_mf.get_rule("app").unwrap();
        assert!(!app_rule.is_phony);
        assert_eq!(app_rule.prereqs, vec!["main.o", "util.o"]);
        assert_eq!(app_rule.commands, vec!["gcc main.o util.o -o app"]);
    }
}
